const ap = new APlayer({
    container: document.getElementById('aplayer'),
    fixed: true,
    autoplay: false,
    order: 'random',
    preload: 'auto',
    mutex: true,
    lrcType: 3,
    audio: [
      {
        name: "晴天",
        artist: "周杰伦",
        url: "/medias/music/qingt.mp3",
        cover: "/medias/music/qingt.jpg",
        lrc: "/medias/music/qingt.lrc",
      },
      {
        name: "青鸟",
        artist: "生物股长",
        url: "/medias/music/qingniao.mp3",
        cover: "/medias/music/qingniao.jpg",
        lrc: "/medias/music/qingniao.lrc",
      },
      {
        name: "everything i wanted",
        artist: "Billie Eilish",
        url: "/medias/music/everythingiwanted.mp3",
        cover: "/medias/music/everythingiwanted.jpg",
        lrc: "/medias/music/everythingiwanted.lrc",
      },
      {
        name: "Other Side",
        artist: "雅-MIYAVI",
        url: "/medias/music/OtherSide.mp3",
        cover: "/medias/music/OtherSide.jpg",
        lrc: "/medias/music/OtherSide.lrc",
      },
      {
        name: "以父之名",
        artist: "周杰伦",
        url: "/medias/music/yifuzm.mp3",
        cover: "/medias/music/yifuzm.jpg",
        lrc: "/medias/music/yifuzm.lrc",
      },
      {
        name: "Something Just Like This",
        artist: "Coldplay",
        url: "/medias/music/SomethingJust.mp3",
        cover: "/medias/music/SomethingJust.jpg",
        lrc: "/medias/music/SomethingJust.lrc",
      },
      {
        name: "光るなら",
        artist: "Goose house",
        url: "/medias/music/guang.mp3",
        cover: "/medias/music/guang.jpg",
        lrc: "/medias/music/guang.lrc",
      },
      {
        name: "山海",
        artist: "草东没有派对",
        url: "/medias/music/shanhai.mp3",
        cover: "/medias/music/shanhai.jpg",
        lrc: "/medias/music/shanhai.lrc",
      },
      {
        name: "异度侵入片头曲",
        artist: "Sou",
        url: "https://sharefs.yun.kugou.com/202002230119/c355e85c84e7b62c63c3b7013ff986dc/G191/M09/05/0B/X4cBAF4Sj0iAcecWADWuVe9xtII389.mp3",
        cover: "/medias/music/yiduSou.jpg",
        lrc: "/medias/music/yiduSou.lrc",
      },
      {
        name: "一路向北 (Live)",
        artist: "周杰伦",
        url: "/medias/music/yilxb.mp3",
        cover: "/medias/music/yilxb.jpg",
        lrc: "/medias/music/yilxb.lrc",
      },
    ]
});